### ISSUE TITLE
and with a rooted phone ?

### ISSUE THREAD

**Issue by ghost** [DarkMetalMouse/razerduino#2]
Hi, I haven't any arduino but i have a rooted phone. Can i do something to get the same result ?

**Comment by DarkMetalMouse** [comment]
It's probably possible with a custom ROM but adb and fastboot drivers only work with certain VIDs, so you won't be able to use them once you flash your phone unless you find a way to edit the drivers. Seems like more trouble than it's worth, an Arduino costs only a few dollars.
